name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deps
      run: apt-get install clang-6.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
